### ISSUE TITLE
很可惜停更了

### ISSUE THREAD

**Issue by axetroy** [HalfStackDeveloper/FloatBall#4]
市面上还没有一款悬浮球做的比魅族好，手势体验也没有这个好。

对于大屏的安卓原生系统来说，悬浮球很重要。
以为着不用再care底部的三大金刚，单手就能完成操作。

如果做出UI，能设置参数，优化滑动效果。发布应用，能秒杀其他悬浮球APP

**Comment by HalfStackDeveloper** [comment]
主要是后来觉得满足了自己的日常使用，欢迎大家提代码进行优化😀

**Comment by axetroy** [comment]
@HalfStackDeveloper 
不会安卓开发的痛...还做不到可用的产品，没人PR的...

这么好的悬浮球，比其他同类产品，仿ios的花俏应用，好的不要太多

**Comment by selcarpa** [comment]
> 主要是后来觉得满足了自己的日常使用，欢迎大家提代码进行优化😀
请问这个项目是开源的吗？什么协议呢，看了看没找到开源协议之类的说法，我也觉得很好用，想要单独做个分支，虽然目前我安卓学得不多.
